openapi: 3.0.0
info:
  title: SwagTest
  description: SwagTest documentation
  version: '1.0'
  termsOfService: 'https://example.org'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'

servers:
  - url: //lightning-backend.acomodeo.com/api

tags:
  - name: properties
    description: Properties

paths:

  /properties:
    head:
      tags:
        - properties
      summary: Get property metadata
      description: Get metadata about all properties you have access to.
      operationId: getPropertiesHeader
      responses:
        default:
          description: Default response

    get:
      tags:
        - properties
      summary: Get properties
      description: Get all properties you have access to.
      operationId: getProperties
      parameters:
        - name: businessUnit.ancestors
          in: query
          description: businessUnit.ancestors
          required: false
          schema:
            type: string
        - name: businessUnit.parent
          in: query
          description: businessUnit.parent
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

    post:
      tags:
        - properties
      summary: Create property
      description: Create a new property
      operationId: createProperty
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      requestBody:
        $ref: '#/components/requestBodies/Property'

components:
  requestBodies:

    PropertyRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Property'
      description: property
      required: true

  schemas:

    Locale:
      description: ISO standard locale/country string
      type: string

    Address:
      description: Standard street address
      type: object
      properties:
        company:
          description: Optional company part of address
          example: Super Comapny Inc.
          type: string
        countries:
          description: Country as 2-letter ISO code
          example: US
          type: array
          items:
            type: string
      required:
        - countries

    Tax:
      type: object
      properties:
        test:
          type: array
          items:
            type: object
            properties:
              hello:
                type: string
        type:
          description: Tax type
          example: City Tax
          type: string
        amount:
          title: TaxAmount
          type: object
          properties:
            value:
              description: Amount as number without a unit
              example: 19
              type: number
            unit:
              description: Unit of the amount (percent or currency)
              example: percent
              type: string
              enum:
                - percent
                - currency
        chargeBase:
          description: The multiplier that is used to calculate the tax
          example: perPersonPerNight
          type: string
          enum:
            - perStay
            - perPersonPerStay
            - perPersonPerNight
      required:
        - type
        - amount

    BillRequest:
      type: object
      properties:
        booking:
          $ref: '#/components/schemas/Booking'
        openBills:
          type: array
          items:
            $ref: '#/components/schemas/FilerBill'
